#remember to start at 2nd square at starting place. 
from PortMap import *
driveBase.straight(655)
driveBase.turn(-45)
driveBase.straight(210)
driveBase.straight(-120)
driveBase.turn(45)
driveBase.straight(50)
driveBase.turn(90)
driveBase.straight(455)
#driveBase.()
driveBase.turn(90)
driveBase.straight(-220)
driveBase.straight(80)
driveBase.straight(-220)
driveBase.straight(80)
driveBase.turn(90)
driveBase.straight(535)
driveBase.turn(90)
driveBase.straight(-645)