from PortMap import *
driveBase.straight(645)
driveBase.turn(-45)
driveBase.straight(180)
driveBase.straight(-120)
driveBase.turn(45)
driveBase.straight(60)
driveBase.turn(90)
driveBase.straight(455)
#driveBase.()
driveBase.turn(90)
driveBase.straight(-230)
driveBase.straight(100)